//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarComponentsWPF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarCompDB8Entities : DbContext
    {
        public CarCompDB8Entities()
            : base("name=CarCompDB8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<ComponentType> ComponentTypes { get; set; }
        public virtual DbSet<Manufacter> Manufacters { get; set; }
        public virtual DbSet<ProviderComponent> ProviderComponents { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AllCarComonentsFromProvidersVIEW> AllCarComonentsFromProvidersVIEWs { get; set; }
        public virtual DbSet<AllCarComonentsVIEW> AllCarComonentsVIEWs { get; set; }
        public virtual DbSet<CompProviderCROSSJOIN> CompProviderCROSSJOINs { get; set; }
        public virtual DbSet<ManTypModCROSSJOIN> ManTypModCROSSJOINs { get; set; }
    
        public virtual ObjectResult<TestProcedure1_Result> TestProcedure1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestProcedure1_Result>("TestProcedure1");
        }
    
        public virtual ObjectResult<TestProcedure2_Result> TestProcedure2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestProcedure2_Result>("TestProcedure2");
        }
    }
}
