//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarComponentsWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManTypModCROSSJOIN
    {
        public string Manufacter { get; set; }
        public string CompType { get; set; }
        public string CarModel { get; set; }
    }
}
